Update visual identity
ProjetAGIR/projet-agir pull request #23
Opened 2024-02-22 10:21 UTC by artur0312

2024-02-22 13:37 UTC, cfstcyr requested changes
Super! Par contre, il manque le ticket AGIR-17 à faire. Peut-être juste demander à ChatGPT de le réécrire pour dire que c'est un projet pour l'INSA.pas besoin de quelque chose fancy

2024-02-22 13:37 UTC, cfstcyr commented on packages/client/src/modules/user-profile/components/user-profile-card/user-profile-card.component.scss
> +                    color: lime;
Est-ce que ça t'irait de mettre une autre couleur que ce vert? Il est très flash. Je propose `#66bd80`
<img width="62" alt="Screenshot 2024-02-22 at 14 35 14" src="https://github.com/ProjetAGIR/projet-agir/assets/20962021/53a0d7a6-cec9-4ce6-9ed5-1ede5112cc3f">

2024-02-22 15:40 UTC, cfstcyr requested changes

2024-02-22 15:40 UTC, cfstcyr commented on packages/client/src/modules/user-profile/components/user-profile-card/user-profile-card.component.html
> +                    <i class="user-profile__main__swipe__icon fas fa-thumbs-up" [style.scale]="likeScale"></i>
This icon is there two times. It also appears when the card is opened. Now it is still a hearth 
<img width="89" alt="Screenshot 2024-02-22 at 16 39 11" src="https://github.com/ProjetAGIR/projet-agir/assets/20962021/54323828-5eb3-4b0f-b051-ecd492ba03eb">

2024-03-14 10:00 UTC, artur0312 commented on packages/client/src/modules/user-profile/components/user-profile-card/user-profile-card.component.scss
> +                    color: lime;
J'ai changé la coleur de lime à la couleur proposé

2024-03-14 10:01 UTC, arturvpereira commented
J'ai traité tous les commentaires. Je pense qu'on peut merge maintenant

2024-03-14 10:15 UTC, cfstcyr approved these changes

2024-03-21 17:15 UTC, merged